blog/urls.py
from django.urls import path
from . import views


app_name = 'blog' # упорядочиваем пути в соответствии с названием приложения

urlpatterns = [
    path('', views.post_list, name='post_list'),  # путь для всех постов
   # path('', views.PostListView.as_view(), name='post_list'), # путь для всех посто на основе классов
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),  # путь для одного поста
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):  # метод возвращает отфильтрованные посты
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.SlugField(max_length=250, verbose_name='Слаг', unique_for_date='publish')  # слаг уникальный
    author = models.ForeignKey(User, verbose_name='Автор',
                               # связь данной модели с встроенной моделью User - многие к одному
                               on_delete=models.CASCADE,  # вариант удаления связанных сущностей
                               related_name='blog_posts')  # обратная связь от User к Post(user.blog_posts)
    body = models.TextField(verbose_name='Текст')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Время публикации')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT,
                              verbose_name='Статус')
    objects = models.Manager()  # менеджер применяемый по умолчанию
    published = PublishedManager()  # конкретно-прикладной менеджер
    tags = TaggableManager(verbose_name='Тэг')

    class Meta:  # это класс определяет метаданные модели
        ordering = ['-publish']  # предустановка сортировки по полю publish по умолчанию
        indexes = [
            models.Index(fields=['-publish']),  # индекс повысит скорость запросов фильтрующих по данному полю
        ]
        verbose_name = 'Пост'  # меняю отображение слова пост в амин-панели на русский
        verbose_name_plural = 'Посты'  # множественное число

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])  # динамически сформированный адрес

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments' )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
    def __str__(self):
        return f"Комментарий {self.name} на {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)  # имя человека отправляющего пост
    email = forms.EmailField()  # почта отправившего пост
    to = forms.EmailField()  # почта получателя поста
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)  # комментарий отправленный сообщением по электронной почте

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.views.decorators.http import require_POST
from taggit.models import Tag


class PostListView(ListView):  # отображение списка постов реализованное на основе класса ListView
    queryset = Post.published.all()
    context_object_name = 'posts'  # результат запроса
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request,tag_slug=None):
    post_list = Post.published.all()  # извлекаются все посты при помощи ранее созданного менеджера
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)  # постраничная разбивка
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)  # если номер страницы не int то выдавать первую страницу
    except EmptyPage:
        posts = paginator.page(
            paginator.num_pages)  # если номер страницы находится в не диапазона то показать последнюю
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})  # прорисовка шаблона


def post_detail(request, year, month, day, post):  # извлекаю пост по id и в render отправляю в шаблон
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)  # функция либо извлекает пост либо выдает исключение
    comments = post.comments.filter(active=True) # список активных комментариев к этому посту
    form = CommentForm()

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'form': form})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'dzygun-roman@mail.ru',
                      [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/comment.html',
                  {'post': post,
                   'form': form,
                   'comment': comment})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>Мой блог</h2>
    <p>Это мой блог.</p>
</div>
</body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %} Добавить комментарий {% endblock %}

{% block content %}
{% if comment %}
<h2>Ваш комментарий был добавлен.</h2>
<p><a href="{{ post.get_absolute_url }}"> Вернуться к посту</a></p>
{% else %}
{% include "blog/post/includes/comment_form.html" %}
{% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Share this post
    </a>
  </p>
  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}
  {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Добавить новый комментарий </h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
{{ form.as_p }}
{% csrf_token %}
<p><input type="submit" value="Добавить комментарий"></p>
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Мой блог{% endblock %}

{% block content %}
<h1>Мой блог</h1>
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h2>
<p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
<p class="date">
    Опубликован {{ post.publish }} кем {{ post.author }}
</p>
{{ post.body|truncatewords:30|linebreaks }}
{% endfor %}
{% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Поделиться постом{% endblock %}

{% block content %}
   {% if sent %}
      <h1>Письмо спешно отправлено!</h1>
      <p>
          "{{ post.title }}" было успешно отправлено по адресу {{ form.cleaned_data.to }}.
      </p>
   {% else %}
      <h1>Отправьте "{{ post.title }}" по почте</h1>
      <form method="post">
          {{ form.as_p }}
          {% csrf_token %}
          <input type="submit" value="Отправить письмо">
      </form>
   {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
        {% endif %}
        <span class="current">
            C {{ page.number }} по {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Следующая</a>
        {% endif %}
    </span>
</div>